import "./globals.css";
import { Roboto } from "next/font/google";

// Initialize the Roboto font with specific options
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply roboto.className to the body element */}
      <body className={`${roboto.className} antialiased`}>{children}</body>
    </html>
  );
}
